### ISSUE TITLE
[BUG] Server Crash

### ISSUE THREAD

**Issue by IridiumLLC** [IridiumLLC/IridiumSkyblock#168]
**Describe the bug**
If you Right Click an Island Crystal on Air the server will crash. This only happens on 1.16

**To Reproduce**
1. Make sure you are running 1.16
2. Go to Island bank
3. Withdraw Island Crystals
4. Right click on Air

**Server Error**
```
java.lang.AssertionError: TRAP
	at net.minecraft.server.v1_16_R1.ItemStack.checkEmpty(ItemStack.java:99) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.ItemStack.setCount(ItemStack.java:884) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:407) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1352) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:28) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(SourceFile:144) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(SourceFile:118) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:941) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:918) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:850) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.1.jar:git-Spigot-758abbe-2b00831]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

No clue why this is caused, Ill look more into it later, If anyone has any ideas id appreciate your input as Im not quite sure why this is caused

**Comment by IridiumLLC** [comment]
Looks like an issue caused by Spigot, Latest version of PaperSpigot fixes this
