### ISSUE TITLE
[BUG] ClassCastException for Island Value

### ISSUE THREAD

**Issue by meowsome** [IridiumLLC/IridiumSkyblock#184]
**Describe the bug**
A "ClassCastException" is thrown every time I try to place or destroy certain blocks to make my island value go up. The block places and destroys fine and my island value appears to increase when I place and decrease when I destroy these blocks, but the errors show up.

**To Reproduce**
1. Use the default generated blockvalues.json file
2. Try and place different blocks on your island such as emerald block or any spawner
3. See error in console

**Versions**
MC: Paper 91 for 1.16.1
IridiumSkyblock: 2.4.6

**Error**
```
>.... [23:12:07 WARN]: java.lang.ClassCastException: org.bukkit.material.MaterialData cannot be cast to org.bukkit.material.Crops
>.... [23:12:07 WARN]: at com.iridium.iridiumskyblock.listeners.BlockPlaceListener.onBlockPlace(BlockPlaceListener.java:72)
>.... [23:12:07 WARN]: at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor234.execute(Unknown Source)
>.... [23:12:07 WARN]: at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
>.... [23:12:07 WARN]: at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
>.... [23:12:07 WARN]: at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
>.... [23:12:07 WARN]: at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
>.... [23:12:07 WARN]: at org.bukkit.craftbukkit.v1_16_R1.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:372)
>.... [23:12:07 WARN]: at net.minecraft.server.v1_16_R1.ItemStack.placeItem(ItemStack.java:280)
>.... [23:12:07 WARN]: at net.minecraft.server.v1_16_R1.PlayerInteractManager.a(PlayerInteractManager.java:522)
>.... [23:12:07 WARN]: at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1449)
>.... [23:12:07 WARN]: at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27)
>.... [23:12:07 WARN]: at net.minecraft.server.v1_16_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5)
>.... [23:12:07 WARN]: at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
>.... [23:12:07 WARN]: at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
>.... [23:12:07 WARN]: at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
>.... [23:12:07 WARN]: at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
>.... [23:12:07 WARN]: at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
>.... [23:12:07 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136)
>.... [23:12:07 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129)
>.... [23:12:07 WARN]: at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
>.... [23:12:07 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090)
>.... [23:12:07 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004)
>.... [23:12:07 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
>.... [23:12:07 WARN]: at java.lang.Thread.run(Thread.java:748)
```

**Comment by Erorserv** [comment]
I'm also getting this issue. Paper-113.

**Comment by Spildunky** [comment]
I am also getting this issue...

**Comment by MertUnverdi** [comment]
guys you're still getting this error?

**Comment by IridiumLLC** [comment]
Fixed
