### ISSUE TITLE
[BUG] Could not pass event PlayerBucketEmptyEvent to IridiumSkyblock v2.4.6

### ISSUE THREAD

**Issue by iceBear67** [IridiumLLC/IridiumSkyblock#228]
**Describe the bug**
using lava bucket.
> Could not pass event PlayerBucketEmptyEvent to IridiumSkyblock v2.4.6
java.lang.NoSuchMethodError: org.bukkit.event.player.PlayerBucketEmptyEvent.getBlock()Lorg/bukkit/block/Block;
	at com.iridium.iridiumskyblock.listeners.PlayerBucketEmptyListener.onBucketEmpty(PlayerBucketEmptyListener.java:29) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor934.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.13.2.jar:git-Paper-655]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:520) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.getPlayerBucketEvent(CraftEventFactory.java:271) ~[patched_1.13.2.jar:git-Paper-655]
	at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerBucketEmptyEvent(CraftEventFactory.java:243) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.ItemBucket.a(ItemBucket.java:141) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.ItemBucket.a(ItemBucket.java:65) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.ItemStack.a(ItemStack.java:336) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:419) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1401) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:26) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:5) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[patched_1.13.2.jar:git-Paper-655]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_211]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1018) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[patched_1.13.2.jar:git-Paper-655]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[patched_1.13.2.jar:git-Paper-655]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[01:42:30] [Thread-59/INFO]: [NBTAPI] [NBTAPI] The NBT-API seems to be up-to-date!

Using the latest version from github action,
the line 29:
```java
        if (supports) {
>            block = event.getBlock();
        } else {
```
var supports:`public final boolean supports = XMaterial.supports(13);`
ur..It seems like you locked the argument of `XMaterial.support` then caused this problem?
or something else?.......

**To Reproduce**
1. fill lava by using lavabucket ( Paper 1.13.2 )
2. See error

**Screenshots**
-

**Comment by IridiumLLC** [comment]
Already been fixed

**Comment by iceBear67** [comment]
![screenshot.png](https://i.loli.net/2020/08/15/VX4pOMUm9T36Lki.png)
