### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by PotenciaMax** [IridiumLLC/IridiumSkyblock#238]
**Describe the bug**
When i update the IridiumSkyBlock for 2.4.7 i have this error on my console every 10 seconds:
(This error only occurs when i have islands in IslandManager file)

ERROR IN TacoSpigot:

[16:19:49 WARN]: [IridiumSkyblock] Task #813 for IridiumSkyblock v2.4.7 generated an exception
java.lang.NullPointerException
        at com.iridium.iridiumskyblock.Island.initBlocks(Island.java:256) ~[?:?]
        at com.iridium.iridiumskyblock.IridiumSkyblock$2.run(IridiumSkyblock.java:489) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[spigot.jar:git-TacoSpigot-"95870a93"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349) [spigot.jar:git-TacoSpigot-"95870a93"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:785) [spigot.jar:git-TacoSpigot-"95870a93"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-TacoSpigot-"95870a93"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:715) [spigot.jar:git-TacoSpigot-"95870a93"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:618) [spigot.jar:git-TacoSpigot-"95870a93"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

ERROR IN PaperSpigot

[17:02:38 WARN]: [IridiumSkyblock] Task #733 for IridiumSkyblock v2.4.7 generated an exception
java.lang.NullPointerException
        at com.iridium.iridiumskyblock.Island.initBlocks(Island.java:256) ~[?:?]
        at com.iridium.iridiumskyblock.IridiumSkyblock$2.run(IridiumSkyblock.java:489) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59) ~[spigot.jar:git-PaperSpigot-"4c7641d"]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:352) [spigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:783) [spigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [spigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [spigot.jar:git-PaperSpigot-"4c7641d"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [spigot.jar:git-PaperSpigot-"4c7641d"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]

**To Reproduce**
Enable IridiumSkyBlock 2.4.7 In Spigot 1.8.8

**Comment by IridiumLLC** [comment]
Already fixed this issue, 2.4.7 contains alot of issues though, I recommend you downgrade to 2.4.6 temperately
