### ISSUE TITLE
[BUG] NoSuchMethodError: UltimateStacker.getSpawnerStackManager()

### ISSUE THREAD

**Issue by octo-kumo** [IridiumLLC/IridiumSkyblock#247]
**Describe the bug**
When used with UltimateStacker, the console is spammed with this error message
```
[12:17:03 WARN]: [IridiumSkyblock] Task #28747 for IridiumSkyblock v2.4.7 generated an exception
java.lang.NoSuchMethodError: com.songoda.ultimatestacker.UltimateStacker.getSpawnerStackManager()Lcom/songoda/ultimatestacker/spawner/SpawnerStackManager;
	at com.iridium.iridiumskyblock.support.UltimateStacker.getSpawnerAmount(UltimateStacker.java:16) ~[?:?]
	at com.iridium.iridiumskyblock.Island.calculateIslandValue(Island.java:544) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.2.jar:git-Paper-184]
	at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.2.jar:git-Paper-184]
	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.16.2.jar:git-Paper-184]
	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:375) ~[patched_1.16.2.jar:git-Paper-184]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.2.jar:git-Paper-184]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.2.jar:git-Paper-184]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-184]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
```
Since there exists a class `com.iridium.iridiumskyblock.support.UltimateStacker`, I suppose support for Ultimate Stacker is intended and hence this is a bug.
There are no noticeable issues in-game, however it is not nice to spam the console.

**To Reproduce**
1. Download UltimateStacker and IridiumSkyblock
2. Use paper build 184
3. Run server

**Screenshots**

**Comment by octo-kumo** [comment]
I suspect, this is because you are not using Ultimate Stacker 2.0.X, since they recently updated into a major version, it is possible that old apis are now broken

**Comment by IridiumLLC** [comment]
Ill look into the new UltimateStacker api's soon i recomend you downgrade versions until then
