### ISSUE TITLE
Warn - Exception Executing ConcurrentModificationException

### ISSUE THREAD

**Issue by AlphaDelta23** [IridiumLLC/IridiumSkyblock#249]
Skyblock v2.4.8
PaperMC v387
MC v1.15.2

**Describe the bug**
Warn spamming console:
```[08:48:05] [Craft Scheduler Thread - 36/WARN]: [IridiumSkyblock] Plugin IridiumSkyblock v2.4.8 generated an exception while executing task 3782
java.util.ConcurrentModificationException: null
	at java.util.HashMap.compute(HashMap.java:1229) ~[?:?]
	at com.iridium.iridiumskyblock.Island.lambda$initBlocks$3(Island.java:322) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-387]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-387]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-387]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[08:49:05] [Craft Scheduler Thread - 26/WARN]: [IridiumSkyblock] Plugin IridiumSkyblock v2.4.8 generated an exception while executing task 3843
java.util.ConcurrentModificationException: null
	at java.util.HashMap.compute(HashMap.java:1229) ~[?:?]
	at com.iridium.iridiumskyblock.Island.lambda$initBlocks$3(Island.java:322) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-387]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-387]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-387]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[08:50:05] [Craft Scheduler Thread - 44/WARN]: [IridiumSkyblock] Plugin IridiumSkyblock v2.4.8 generated an exception while executing task 3914
java.util.ConcurrentModificationException: null
	at java.util.HashMap.compute(HashMap.java:1229) ~[?:?]
	at com.iridium.iridiumskyblock.Island.lambda$initBlocks$1(Island.java:286) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-387]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-387]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-387]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]```

**To Reproduce**
Occurs at server start

**Comment by terrarier2111** [comment]
This happens because since Java 9 the ConcurrentHashMap throws ConcurrentModificationExceptions. If you change your Java version this could be the fix for you, but of course the problem should be fixed instead of forcing the user to use a workaround.
