### ISSUE TITLE
[BUG] BIG ISLAND VALUE BUG (WILLING TO PAY)

### ISSUE THREAD

**Issue by TheRealRude** [IridiumLLC/IridiumSkyblock#299]
My current island value is 70.6, however.. this is my value config:
{
  "blockvalue": {
    "DIAMOND_BLOCK": 10.0,
    "IRON_BLOCK": 3.0,
    "EMERALD_BLOCK": 20.0,
    "BEACON": 100.0,
    "GOLD_BLOCK": 5.0
  },
  "spawnervalue": {}
}
It all ends with .0 how can i have 70,6?
Island value goes up and down, especially when i use /is recalc.
Sometimes u have 0 island value, sometimes you have 15k island value, and you change nothing.

Some time ago I noticed that i had UltimateStacker plugin conflicting with Iridium skyblock due to the spawner values.
I afterwards removed all spawner values ^^^
I have been looking but theres nothing i can config tochange this so im depending on you.

**Comment by TheRealRude** [comment]
java.util.ConcurrentModificationException: null
at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_262]
at java.util.HashMap$EntryIterator.next(HashMap.java:1479) ~[?:1.8.0_262]
at java.util.HashMap$EntryIterator.next(HashMap.java:1477) ~[?:1.8.0_262]
at com.iridium.iridiumskyblock.Island.calculateIslandValue(Island.java:490) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-90]
at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-90]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-90]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]

**Comment by IridiumLLC** [comment]
A fix for this will be released tomorrow
