### ISSUE TITLE
[BUG]calculateIslandValue

### ISSUE THREAD

**Issue by daxoneczek** [IridiumLLC/IridiumSkyblock#339]
[12:25:09 WARN]: [IridiumSkyblock] Task #346 for IridiumSkyblock v2.5.4 generated an exception
java.lang.NullPointerException: null
at com.iridium.iridiumskyblock.Island.calculateIslandValue(Island.java:591) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-149]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.2.jar:git-Paper-149]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1185) ~[patched_1.15.2.jar:git-Paper-149]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-149]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-149]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-149]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]

**Comment by MertUnverdi** [comment]
If Your issue already fixed please close this report
You can join our discord server
discord.gg/PTpg4fD
