### ISSUE TITLE
[BUG]Error on consolee from island manageer

### ISSUE THREAD

**Issue by aenaveen** [IridiumLLC/IridiumSkyblock#39]
**Describe the bug**
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
[11:24:26 WARN]:        at java.io.WinNTFileSystem.createFileExclusively(Native Method)
[11:24:26 WARN]:        at java.io.File.createNewFile(Unknown Source)
[11:24:26 WARN]:        at com.iridium.iridiumskyblock.serializer.Persist.save(Persist.java:75)
[11:24:26 WARN]:        at com.iridium.iridiumskyblock.IridiumSkyblock.backupIslandManager(IridiumSkyblock.java:188)

**Comment by IridiumLLC** [comment]
Fixed, join my discord and download the latest beta-version or wait until 2.2.5 releases tomorrow
