### ISSUE TITLE
[BUG] NetherWarts not instance of Crops

### ISSUE THREAD

**Issue by tommasobenatti** [IridiumLLC/IridiumSkyblock#440]
**Describe the bug**
The console of my server is getting spammed with this error

**To Reproduce**
Do a farm of NetherWarts like this (https://www.minecraftexperience.it/images/farm.png) and sometimes you will get the error

**Console Error**
[13:38:35 WARN]: java.lang.IllegalArgumentException: Provided data is not of type org.bukkit.material.NetherWarts, found org.bukkit.material.Crops
-- | --
[13:38:35 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.block.CraftBlockState.setData(CraftBlockState.java:116) 
[13:38:35 WARN]:        at com.iridium.iridiumskyblock.listeners.BlockGrowListener.onBlockGrow(BlockGrowListener.java:38)[13:38:35 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor699.execute(Unknown Source)
[13:38:35 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[13:38:35 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[13:38:35 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:38:35 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607)
[13:38:35 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.handleBlockGrowEvent(CraftEventFactory.java:1143)
[13:38:35 WARN]:        at net.minecraft.server.v1_16_R2.BlockNetherWart.tick(BlockNetherWart.java:36)
[13:38:35 WARN]:        at net.minecraft.server.v1_16_R2.BlockBase$BlockData.b(BlockBase.java:584)
[13:38:35 WARN]:        at net.minecraft.server.v1_16_R2.WorldServer.a(WorldServer.java:1136)
[13:38:35 WARN]:        at net.minecraft.server.v1_16_R2.ChunkProviderServer.tickChunks(ChunkProviderServer.java:1034)
[13:38:35 WARN]:        at net.minecraft.server.v1_16_R2.ChunkProviderServer.tick(ChunkProviderServer.java:926)
[13:38:35 WARN]:        at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:887)
[13:38:35 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1430)
[13:38:35 WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:391)
[13:38:35 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1278)
[13:38:35 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1009)
[13:38:35 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:178)
[13:38:35 WARN]:        at java.lang.Thread.run(Thread.java:748)

**Screenshots**
https://www.minecraftexperience.it/images/farm.png

**Comment by dlsf** [comment]
This has been fixed by #542
