### ISSUE TITLE
[BUG] This Warn is Flooding my console (PAPER 1.8.8)

### ISSUE THREAD

**Issue by PotenciaMax** [IridiumLLC/IridiumSkyblock#509]
Version: IridumSkyBlock 2.6.7

**Console Error**

[20:00:47 WARN]: [HikariPool-1 housekeeper] WARN com.zaxxer.hikari.pool.ProxyLeakTask - Connection leak detection triggered for com.mysql.jdbc.JDBC4Connection@4d95c44a on thread Craft Scheduler Thread - 215, stack trace follows
[20:00:47 WARN]: java.lang.Exception: Apparent connection leak detected
[20:00:47 WARN]:        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
[20:00:47 WARN]:        at com.iridium.iridiumskyblock.managers.SQLManager.getConnection(SQLManager.java:90)
[20:00:47 WARN]:        at com.iridium.iridiumskyblock.IridiumSkyblock.saveData(IridiumSkyblock.java:755)
[20:00:47 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
[20:00:47 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[20:00:47 WARN]:        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
[20:00:47 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20:00:47 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20:00:47 WARN]:        at java.lang.Thread.run(Unknown Source)
[20:00:52 WARN]: [Craft Scheduler Thread - 215] INFO com.zaxxer.hikari.pool.ProxyLeakTask - Previously reported leaked connection com.mysql.jdbc.JDBC4Connection@4d95c44a on thread Craft Scheduler Thread - 215 was returned to the pool (unleaked)

**Comment by BomBardyGamer** [comment]
Hello! Can you please provide me with steps on how to reproduce this?

**Comment by BomBardyGamer** [comment]
Hello! It seems as if the connection pooling library (the thing that connects to the database) has detected a connection leak (a connection not fully shut down). We will look in to this as soon as possible!

Thanks for the report!
