### ISSUE TITLE
[BUG] BlockExplodeEvent

### ISSUE THREAD

**Issue by Kiroslawa93** [IridiumLLC/IridiumSkyblock#516]
Hi i have a bug in console can you help me with this
![skyblock](https://user-images.githubusercontent.com/77406316/104487913-f90d7f00-55cd-11eb-8c7b-5a67bdd73c89.png)

**Comment by PeachesMLG** [comment]
can You copy and paste the error instead of sending a screenshot with half of it being cut off

**Comment by Kiroslawa93** [comment]
[18:30:11 ERROR]: Could not pass event BlockExplodeEvent to IridiumSkyblock v2.6.7
java.lang.NullPointerException: null
at com.iridium.iridiumskyblock.listeners.EntityExplodeListener.onBlockExplode(EntityExplodeListener.java:68) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor864.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-407]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-407]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-407]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-407]
at net.minecraft.server.v1_16_R3.Explosion.a(Explosion.java:266) ~[patched_1.16.4.jar:git-Paper-407]
at net.minecraft.server.v1_16_R3.World.createExplosion(World.java:920) ~[patched_1.16.4.jar:git-Paper-407]
at net.minecraft.server.v1_16_R3.WorldServer.createExplosion(WorldServer.java:1605) ~[patched_1.16.4.jar:git-Paper-407]
at net.minecraft.server.v1_16_R3.BlockBed.explodeBed(BlockBed.java:91) ~[patched_1.16.4.jar:git-Paper-407]
at net.minecraft.server.v1_16_R3.BlockBed.lambda$interact$0(BlockBed.java:67) ~[patched_1.16.4.jar:git-Paper-407]
at com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43) ~[patched_1.16.4.jar:git-Paper-407]
at net.minecraft.server.v1_16_R3.BlockBed.interact(BlockBed.java:64) ~[patched_1.16.4.jar:git-Paper-407]
at net.minecraft.server.v1_16_R3.BlockBase$BlockData.interact(BlockBase.java:585) ~[patched_1.16.4.jar:git-Paper-407]
at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:515) ~[patched_1.16.4.jar:git-Paper-407]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1549) ~[patched_1.16.4.jar:git-Paper-407]
at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.4.jar:git-Paper-407]
at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.4.jar:git-Paper-407]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-407]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-407]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-407]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-407]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-407]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1128) ~[patched_1.16.4.jar:git-Paper-407]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1121) ~[patched_1.16.4.jar:git-Paper-407]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.4.jar:git-Paper-407]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1257) ~[patched_1.16.4.jar:git-Paper-407]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:992) ~[patched_1.16.4.jar:git-Paper-407]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-407]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_261]
