### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by WiredOrange** [IridiumLLC/IridiumSkyblock#517]
**Describe the bug**
When I went onto the Skyblock server, I did /is and then clicked warps. It was completely empty (full of the fill in black glass stained panes) and then the errors just kept coming as long as the player was in the menu

**To Reproduce**
1. Go into /is
2. Click on waprs
3. See error

**Console Error**
`[18:17:29 WARN]: [IridiumSkyblock] Plugin IridiumSkyblock v2.6.7 generated an exception while executing task 4808
java.lang.NullPointerException: null
        at com.iridium.iridiumskyblock.gui.WarpGUI.addContent(WarpGUI.java:30) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-253]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.3.jar:git-Paper-253]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.3.jar:git-Paper-253]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_275]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_275]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]`

**Comment by PeachesMLG** [comment]
99% sure this has been fixed for 3.0.0. Ill leave this open for now until I confirm this
