### ISSUE TITLE
[BUG] can't run

### ISSUE THREAD

**Issue by Frodwo** [IridiumLLC/IridiumSkyblock#543]
[19:48:39] [Server thread/INFO]: [IridiumSkyblock] Enabling IridiumSkyblock v2.6.7
[19:48:39] [Server thread/WARN]: java.lang.NullPointerException
[19:48:39] [Server thread/WARN]: 	at com.iridium.iridiumskyblock.IridiumSkyblock.loadConfigs(IridiumSkyblock.java:611)
[19:48:39] [Server thread/WARN]: 	at com.iridium.iridiumskyblock.IridiumSkyblock.onEnable(IridiumSkyblock.java:127)
[19:48:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[19:48:39] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[19:48:39] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[19:48:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[19:48:39] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[19:48:39] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:217)
[19:48:39] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:941)
[19:48:39] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175)
[19:48:39] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)

version This server is running Purpur version git-Purpur-966 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by dlsf** [comment]
Please join our support Discord, this error is most likely caused by an invalid configuration file. You can find the invite on the SpigotMC page.
