### ISSUE TITLE
[BUG] Island being created inside other islands

### ISSUE THREAD

**Issue by MrMobster** [IridiumLLC/IridiumSkyblock#544]
**Describe the bug**

**To Reproduce**
Im not sure if there is a way to reproduce anything. This was about the 4-5 island generated. The island it was created into was a fully upgraded lvl.3 island but outside that idk xD I didnt mess with the configs as it was a good plugin out the box.

**Console Error**
Not applicable
![bug](https://user-images.githubusercontent.com/78231286/106317433-8cc88780-622b-11eb-8d60-3d6755993e7a.png)

**Screenshots**
https://cdn.discordapp.com/attachments/592092308514537510/804535178420158484/unknown.png

**Comment by dlsf** [comment]
Are you using the latest version of IridiumSkyblock? This could be caused by a bad configuration, a deleted file, or an error when storing the data.

**Comment by LegoLoverGo** [comment]
This also happened on my server.

**Comment by dlsf** [comment]
Did you change the island size or distance between islands with some already generated? Is your distance between islands equal to the size of the max upgrade times 2 plus 1 (or greater)?

**Comment by LegoLoverGo** [comment]
Here is the log

`[Wed, 10. Feb 2021 12:58:28 EST WARN] Plugin IridiumSkyblock v2.6.7 generated an exception while executing task 1011
[Wed, 10. Feb 2021 12:58:58 EST WARN] java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
[Wed, 10. Feb 2021 12:58:58 EST WARN] at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
[Wed, 10. Feb 2021 12:58:58 EST WARN] at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
[Wed, 10. Feb 2021 12:58:58 EST WARN] at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
[Wed, 10. Feb 2021 12:58:58 EST WARN] at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
[Wed, 10. Feb 2021 12:58:58 EST WARN] at com.iridium.iridiumskyblock.managers.SQLManager.getConnection(SQLManager.java:90)
[Wed, 10. Feb 2021 12:58:58 EST WARN] at com.iridium.iridiumskyblock.IridiumSkyblock.saveData(IridiumSkyblock.java:755)
[Wed, 10. Feb 2021 12:58:58 EST WARN] at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[Wed, 10. Feb 2021 12:58:58 EST WARN] at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[Wed, 10. Feb 2021 12:58:58 EST WARN] at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[Wed, 10. Feb 2021 12:58:58 EST WARN] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[Wed, 10. Feb 2021 12:58:58 EST WARN] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[Wed, 10. Feb 2021 12:58:58 EST WARN] at java.lang.Thread.run(Thread.java:748)
[Wed, 10. Feb 2021 12:58:58 EST WARN] Plugin IridiumSkyblock v2.6.7 generated an exception while executing task 1011
[Wed, 10. Feb 2021 12:59:28 EST WARN] java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
[Wed, 10. Feb 2021 12:59:28 EST WARN] at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
[Wed, 10. Feb 2021 12:59:28 EST WARN] at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
[Wed, 10. Feb 2021 12:59:28 EST WARN] at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
[Wed, 10. Feb 2021 12:59:28 EST WARN] at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
[Wed, 10. Feb 2021 12:59:28 EST WARN] at com.iridium.iridiumskyblock.managers.SQLManager.getConnection(SQLManager.java:90)
[Wed, 10. Feb 2021 12:59:28 EST WARN] at com.iridium.iridiumskyblock.IridiumSkyblock.saveData(IridiumSkyblock.java:755)
[Wed, 10. Feb 2021 12:59:28 EST WARN] at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[Wed, 10. Feb 2021 12:59:28 EST WARN] at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[Wed, 10. Feb 2021 12:59:28 EST WARN] at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[Wed, 10. Feb 2021 12:59:28 EST WARN] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[Wed, 10. Feb 2021 12:59:28 EST WARN] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[Wed, 10. Feb 2021 12:59:28 EST WARN] at java.lang.Thread.run(Thread.java:748)
[Wed, 10. Feb 2021 12:59:28 EST WARN] Plugin IridiumSkyblock v2.6.7 generated an exception while executing task 1011
[Wed, 10. Feb 2021 12:59:58 EST WARN] java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30000ms.
[Wed, 10. Feb 2021 12:59:58 EST WARN] at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
[Wed, 10. Feb 2021 12:59:58 EST WARN] at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
[Wed, 10. Feb 2021 12:59:58 EST WARN] at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
[Wed, 10. Feb 2021 12:59:58 EST WARN] at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
[Wed, 10. Feb 2021 12:59:58 EST WARN] at com.iridium.iridiumskyblock.managers.SQLManager.getConnection(SQLManager.java:90)
[Wed, 10. Feb 2021 12:59:58 EST WARN] at com.iridium.iridiumskyblock.IridiumSkyblock.saveData(IridiumSkyblock.java:755)
[Wed, 10. Feb 2021 12:59:58 EST WARN] at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[Wed, 10. Feb 2021 12:59:58 EST WARN] at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[Wed, 10. Feb 2021 12:59:58 EST WARN] at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[Wed, 10. Feb 2021 12:59:58 EST WARN] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[Wed, 10. Feb 2021 12:59:58 EST WARN] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[Wed, 10. Feb 2021 12:59:58 EST WARN] at java.lang.Thread.run(Thread.java:748)`

**Comment by dlsf** [comment]
You have an issue with your SQL connection. We recommend using MySQL at the moment, although the next release (3.0) will fix connection issues if you have the patience to wait.

**Comment by LegoLoverGo** [comment]
I have a MariaDB database already. But how do I convert my database to MySQL?

**Comment by dlsf** [comment]
As far as I know, we currently don't support MariaDB. Please wait until version 3.0

**Comment by LegoLoverGo** [comment]
MariaDB is a drop-in replacement for MySQL

**Comment by dlsf** [comment]
I know that it is a fork of MySQL, but I've heard that it doesn't just work without any changes
