### ISSUE TITLE
[BUG] EpicSpawners

### ISSUE THREAD

**Issue by MystiCub** [IridiumLLC/IridiumSkyblock#549]
Hello good, I wanted to give notice of the following error which appears when putting a spawner (Iron Golem) of the plugin "EpicSpawners".

PaperSpigot: 1.16.4
Java: 8

[IridiumSkyblock] Task #93399 for IridiumSkyblock v2.6.7 generated an exception
java.lang.NoSuchMethodError: com.songoda.epicspawners.spawners.spawner.SpawnerManager.getSpawnerFromWorld(Lorg/bukkit/Location;)Lcom/songoda/epicspawners/spawners/spawner/Spawner;
        at com.iridium.iridiumskyblock.support.EpicSpawners.getSpawnerAmount(EpicSpawners.java:13) ~[?:?]
        at com.iridium.iridiumskyblock.Island.calculateIslandValue(Island.java:468) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[paper-1.16.4.jar:git-Paper-414]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[paper-1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1293) ~[paper-1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[paper-1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1208) ~[paper-1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:996) ~[paper-1.16.4.jar:git-Paper-414]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[paper-1.16.4.jar:git-Paper-414]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

**Comment by dlsf** [comment]
For some reason, they decided to introduce breaking API changes. This issue will be resolved in version 3.0, but as it will take some time to finish, I recommend you use an older version of EpicSpawners.

**Comment by PeachesMLG** [comment]
"For some reason, they decided to introduce breaking API changes"

Not like I can really say much on that matter though :eyes:

**Comment by MystiCub** [comment]
Ok, thanks :)
