### ISSUE TITLE
[BUG] Exception loading entity (Cannot drop air)

### ISSUE THREAD

**Issue by TheRealRude** [IridiumLLC/IridiumSkyblock#559]
[23:54:16 WARN]: Exception loading entity: 
net.minecraft.server.v1_16_R3.ReportedException: Loading entity NBT
        at net.minecraft.server.v1_16_R3.Entity.load(Entity.java:1806) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.EntityTypes.lambda$a$2(EntityTypes.java:338) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.SystemUtils.a(SystemUtils.java:295) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.EntityTypes.a(EntityTypes.java:335) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.EntityTypes.b(EntityTypes.java:383) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.EntityTypes.a(EntityTypes.java:364) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:649) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.ChunkRegionLoader.lambda$createLoadEntitiesConsumer$8(ChunkRegionLoader.java:315) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.Chunk.addEntities(Chunk.java:786) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.PlayerChunkMap.lambda$null$46(PlayerChunkMap.java:1295) ~[patched_1.16.5.jar:git-Paper-457]
        at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[patched_1.16.5.jar:git-Paper-457]
        at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[patched_1.16.5.jar:git-Paper-457]
        at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.PlayerChunkMap.lambda$c$47(PlayerChunkMap.java:1278) ~[patched_1.16.5.jar:git-Paper-457]
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
        at net.minecraft.server.v1_16_R3.ChunkTaskQueueSorter.b(SourceFile:58) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:994) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1041) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:503) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.IChunkProvider.getChunkAt(SourceFile:16) ~[patched_1.16.5.jar:git-Paper-457]
        at org.bukkit.craftbukkit.v1_16_R3.CraftWorld.getChunkAt(CraftWorld.java:421) ~[patched_1.16.5.jar:git-Paper-457]
        at com.iridium.iridiumskyblock.Island.initBlocks(Island.java:205) ~[?:?]
        at com.iridium.iridiumskyblock.IridiumSkyblock$2.run(IridiumSkyblock.java:465) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-457]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-457]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: Cannot drop air
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.EntityItem.setItemStack(EntityItem.java:454) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.EntityItem.loadData(EntityItem.java:330) ~[patched_1.16.5.jar:git-Paper-457]
        at net.minecraft.server.v1_16_R3.Entity.load(Entity.java:1713) ~[patched_1.16.5.jar:git-Paper-457]
        ... 34 more

**Comment by TheRealRude** [comment]
1.16.5

**Comment by dlsf** [comment]
When does the exception occur? Is there an entity on your schematic?

**Comment by TheRealRude** [comment]
No its totally random, 1 on first boot and more just random when players go it island for example?

**Comment by dlsf** [comment]
Is there an entity on your schematic or island? Could you try updating Paper?

**Comment by TheRealRude** [comment]
Yeah there are hoppers in my schematic. And I use the newest version of paper so..

**Comment by dlsf** [comment]
Hoppers are not entities, but armorstands and sheep are. Also, are you sure that you are on the latest version? If so, is the error message still 100% the same?

**Comment by TheRealRude** [comment]
The error is the same and I'm running on of the latest 1.16.5 builds. If hoppers aren't a entity then not.

**Comment by dlsf** [comment]
I'm pretty sure that this is not an issue with IridiumSkyblock. The server falls to load a chunk, so it's maybe corrupted or the server software fails to load it for some other reason. There is not much we can do about it

**Comment by dlsf** [comment]
I'll close this issue now, please join our support Discord and contact me (das_#9677) if you are experiencing any further problems. I don't think that this is something we can solve over a Github issue.
