### ISSUE TITLE
[ERROR] Error started appearing for seemingly no reason

### ISSUE THREAD

**Issue by Elli83** [IridiumLLC/IridiumSkyblock#99]
I started getting the following error for seemingly no reason whenever I run any command.

`28.04 18:33:45 [Server] WARN java.lang.NullPointerException
28.04 18:33:45 [Server] WARN at com.iridium.iridiumskyblock.User.getUser(User.java:62)
28.04 18:33:45 [Server] WARN at com.iridium.iridiumskyblock.commands.CommandManager.onCommand(CommandManager.java:103)
28.04 18:33:45 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
28.04 18:33:45 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
28.04 18:33:45 [Server] WARN at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:753)
28.04 18:33:45 [Server] WARN at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1826)
28.04 18:33:45 [Server] WARN at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1634)
28.04 18:33:45 [Server] WARN at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
28.04 18:33:45 [Server] WARN at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
28.04 18:33:45 [Server] WARN at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
28.04 18:33:45 [Server] WARN at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18)
28.04 18:33:45 [Server] WARN at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
28.04 18:33:45 [Server] WARN at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
28.04 18:33:45 [Server] WARN at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
28.04 18:33:45 [Server] WARN at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1081)
28.04 18:33:45 [Server] WARN at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1074)
28.04 18:33:45 [Server] WARN at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
28.04 18:33:45 [Server] WARN at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1035)
28.04 18:33:45 [Server] WARN at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:950)
28.04 18:33:45 [Server] WARN at java.lang.Thread.run(Thread.java:748)`

**Comment by Elli83** [comment]
20 days and still no word. Easily the worst plugin support I've ever encountered
